<a href="https://colab.research.google.com/github/Shiva-panda/essential-thing/blob/main/numpy_advance_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [174]:
import numpy as np

In [175]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [176]:
a

array([0., 0., 0., 0., 0.])

In [177]:
a.ndim

1

In [178]:
b = np.zeros((3, 4))

In [179]:
b.ndim

2

In [180]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [181]:
np.array([[2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [182]:
arr = np.zeros((3, 4))

In [183]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [184]:
arr.ndim

2

In [185]:
#3 dimensional array
np.zeros(1)

array([0.])

In [186]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [187]:
arr = np.zeros((3, 4))
arr.ndim

2

In [188]:
arr = np.zeros((1, 3, 4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [189]:
arr.ndim

3

In [190]:
arr = np.zeros((1, 1, 3, 4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [191]:
arr.ndim

4

In [192]:
arr = np.zeros((1, 1, 1, 3, 4))
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [193]:
arr.ndim

5

In [194]:
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [195]:
arr = np.ones((3, 4))

In [196]:
arr.ndim

2

In [197]:
arr.shape

(3, 4)

In [198]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [199]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [200]:
a = arr * 5

In [201]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [202]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [203]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [204]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [205]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [206]:
#optional >> random module

import random
random.choice((1, 2, 3, 4, 5))

3

In [207]:
random.choice('Ajay')

'y'

In [208]:
random.randrange(1, 10)

1

In [209]:
random.random() # a random no is generated between 0(included) and 1 (excluded)

0.16643967552129024

In [210]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [211]:
random.shuffle(lis)

In [212]:
lis

[2, 1, 5, 3, 4]

In [213]:
random.uniform(7, 14)

7.147347113590946

In [214]:

#random numbers related concepts in numpy
np.array([])

array([], dtype=float64)

In [215]:
np.random.random_sample()

0.9088609124305183

In [216]:
np.random.random_sample((5, ))

array([0.73539307, 0.01282352, 0.37098847, 0.50242988, 0.58294063])

In [217]:
np.random.rand(1)

array([0.97607561])

In [218]:
np.random.rand(2, 3)

array([[0.45761473, 0.8436824 , 0.44082482],
       [0.28439269, 0.96853898, 0.54325529]])

In [219]:
np.random.randn(2,3)

array([[ 1.03327468,  0.1083945 ,  1.72627619],
       [ 0.04138818, -0.58813134,  0.65064297]])

In [220]:
arr = np.random.randint(1, 5, size= (3, 4))

In [221]:
arr.ndim

2

In [222]:
arr.shape

(3, 4)

In [223]:
arr.size

12

In [224]:
arr

array([[2, 3, 2, 2],
       [1, 2, 2, 2],
       [2, 4, 1, 3]])

In [225]:
#reshaping the array

arr1 = arr.reshape(2, 6)

In [226]:
arr1.shape

(2, 6)

In [227]:
arr1.size

12

In [228]:
arr

array([[2, 3, 2, 2],
       [1, 2, 2, 2],
       [2, 4, 1, 3]])

In [229]:
arr.size

12

In [230]:
#array size will not change, always resape parameter should be multiplication of original array size

In [231]:
arr

array([[2, 3, 2, 2],
       [1, 2, 2, 2],
       [2, 4, 1, 3]])

In [232]:
arr.size

12

In [233]:
arr.reshape(12,1)

array([[2],
       [3],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [4],
       [1],
       [3]])

In [234]:
arr.reshape(1, 12)

array([[2, 3, 2, 2, 1, 2, 2, 2, 2, 4, 1, 3]])

In [235]:
arr.reshape(2,2, 3)

array([[[2, 3, 2],
        [2, 1, 2]],

       [[2, 2, 2],
        [4, 1, 3]]])

In [236]:
arr.reshape(3,4)

array([[2, 3, 2, 2],
       [1, 2, 2, 2],
       [2, 4, 1, 3]])

In [237]:
#case when you dont know in reshape what should be the column count

arr.reshape(4, -1)

array([[2, 3, 2],
       [2, 1, 2],
       [2, 2, 2],
       [4, 1, 3]])

In [238]:
arr.reshape(2, -1)

array([[2, 3, 2, 2, 1, 2],
       [2, 2, 2, 4, 1, 3]])

In [239]:
arr.reshape(2, -100)

array([[2, 3, 2, 2, 1, 2],
       [2, 2, 2, 4, 1, 3]])

In [240]:
arr1 = arr.reshape(-1, 3)#you know column count but no row count

In [241]:
arr1.size

12

In [242]:
arr.reshape(12, 1)

array([[2],
       [3],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [4],
       [1],
       [3]])

In [243]:
arr.reshape(12, 1).base #to see the original array

array([[2, 3, 2, 2],
       [1, 2, 2, 2],
       [2, 4, 1, 3]])

In [244]:
arr.reshape(2, 2, 3)

array([[[2, 3, 2],
        [2, 1, 2]],

       [[2, 2, 2],
        [4, 1, 3]]])

In [245]:
arr.reshape(1, 2, 2, 3)

array([[[[2, 3, 2],
         [2, 1, 2]],

        [[2, 2, 2],
         [4, 1, 3]]]])

In [246]:
arr.reshape(1, 2, 2, 3).ndim

4

In [247]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[2],
        [3],
        [2]],

       [[2],
        [1],
        [2]],

       [[2],
        [2],
        [2]],

       [[4],
        [1],
        [3]]])

In [248]:
#conditions on array

arr1 = np.random.randint(1, 10, (5,6))

In [249]:
arr1

array([[2, 6, 2, 4, 4, 7],
       [9, 3, 2, 4, 5, 9],
       [8, 2, 2, 2, 2, 8],
       [4, 2, 5, 2, 9, 6],
       [1, 2, 9, 1, 5, 3]])

In [250]:
arr1.shape

(5, 6)

In [251]:
arr1.ndim

2

In [252]:
arr1.size

30

In [253]:
arr1 > 3

array([[False,  True, False,  True,  True,  True],
       [ True, False, False,  True,  True,  True],
       [ True, False, False, False, False,  True],
       [ True, False,  True, False,  True,  True],
       [False, False,  True, False,  True, False]])

In [254]:
arr1[arr1> 3]

array([6, 4, 4, 7, 9, 4, 5, 9, 8, 8, 4, 5, 9, 6, 9, 5])

In [255]:
arr1[arr1 < 3]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1])

In [256]:
arr1

array([[2, 6, 2, 4, 4, 7],
       [9, 3, 2, 4, 5, 9],
       [8, 2, 2, 2, 2, 8],
       [4, 2, 5, 2, 9, 6],
       [1, 2, 9, 1, 5, 3]])

In [257]:
#To access elements in the array
arr1[0]

array([2, 6, 2, 4, 4, 7])

In [258]:
arr1[1]

array([9, 3, 2, 4, 5, 9])

In [259]:
arr1[1][0]

np.int64(9)

In [260]:
arr1

array([[2, 6, 2, 4, 4, 7],
       [9, 3, 2, 4, 5, 9],
       [8, 2, 2, 2, 2, 8],
       [4, 2, 5, 2, 9, 6],
       [1, 2, 9, 1, 5, 3]])

In [261]:
arr1[0:3] #oth row, 1st row and 2nd row

array([[2, 6, 2, 4, 4, 7],
       [9, 3, 2, 4, 5, 9],
       [8, 2, 2, 2, 2, 8]])

In [262]:
arr1[0:3, [0, 2]] #0to2nd row and 0th and 2nd column

array([[2, 2],
       [9, 2],
       [8, 2]])

In [263]:
#slicing on both rows and column

In [264]:
arr1

array([[2, 6, 2, 4, 4, 7],
       [9, 3, 2, 4, 5, 9],
       [8, 2, 2, 2, 2, 8],
       [4, 2, 5, 2, 9, 6],
       [1, 2, 9, 1, 5, 3]])

In [265]:
arr1[0:3, 1:3]

array([[6, 2],
       [3, 2],
       [2, 2]])

In [266]:
arr1[0:2, [0,1]]

array([[2, 6],
       [9, 3]])

In [267]:
arr1[0, [1, 3]]

array([6, 4])

In [268]:
arr1[2:4, [0, 3]]

array([[8, 2],
       [4, 2]])

In [269]:
arr1[2:5]

array([[8, 2, 2, 2, 2, 8],
       [4, 2, 5, 2, 9, 6],
       [1, 2, 9, 1, 5, 3]])

In [270]:
arr1[2:5, 0:2]

array([[8, 2],
       [4, 2],
       [1, 2]])

In [271]:
#mathematical operation on two arrays
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [272]:
arr1

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2]])

In [273]:
arr2

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 2]])

In [274]:
arr1+arr2 #indewise elment addition

array([[2, 2, 3],
       [3, 3, 2],
       [3, 4, 4]])

In [275]:
arr1-arr2 #indexwise element substraction

array([[ 0,  0, -1],
       [-1,  1,  0],
       [-1,  0,  0]])

In [276]:
arr1 * arr2 #index wise multiplication

array([[1, 1, 2],
       [2, 2, 1],
       [2, 4, 4]])

In [277]:
arr1, arr2

(array([[1, 1, 1],
        [1, 2, 1],
        [1, 2, 2]]),
 array([[1, 1, 2],
        [2, 1, 1],
        [2, 2, 2]]))

In [278]:
arr1 / arr2 #index wise divison

array([[1. , 1. , 0.5],
       [0.5, 2. , 1. ],
       [0.5, 1. , 1. ]])

In [279]:
#4/0

In [280]:
arr1 / 0 #in python zero divion error will come, but in numpy no error

/tmp/ipython-input-1550714841.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0 #in python zero divion error will come, but in numpy no error


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [281]:
#matric multiplication>> different from index wise multiplication

arr1 @ arr2 #1st way to do matrix multiplication

array([[5, 4, 5],
       [7, 5, 6],
       [9, 7, 8]])

In [282]:
np.dot(arr1, arr2) #ndst way to do matrix multiplication

array([[5, 4, 5],
       [7, 5, 6],
       [9, 7, 8]])

In [283]:
arr = np.zeros((3, 4))

In [284]:
#broadcasting
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [285]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [286]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [287]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [288]:
a = np.array([1, 2, 3, 4])

In [289]:
a

array([1, 2, 3, 4])

In [290]:
a.ndim

1

In [291]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [292]:
a = np.array([[1, 2, 3, 4]])

In [293]:
a

array([[1, 2, 3, 4]])

In [294]:
#Transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [295]:
arr1

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2]])

In [296]:
arr1.T

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [304]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [311]:
import nbformat

# ✅ Corrected paths (include MyDrive)
first_notebook = "/content/drive/sample_data/Data Toolkit/Numpy basics.ipynb"
second_notebook = "/content/drive/sample_data/Data Toolkit/numpy_advance-1ipynb"
merged_notebook = "/content/drive/sample_data/Data toolkit/Merged_Notebook.ipynb"

nb1 = nbformat.read(first_notebook, as_version=4)
nb2 = nbformat.read(second_notebook, as_version=4)

nb1.cells.extend(nb2.cells)
nbformat.write(nb1, merged_notebook)

print("✅ Merged notebook saved at:", merged_notebook)



FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/sample_data/Data Toolkit/Numpy basics.ipynb'

In [310]:
!ls

drive  sample_data
